version: "3.1"
services:
  master:
    build: ./master
    image: treiro/apache-jmeter-master
    ports:
      - "60000:60000"
    networks:
      - jm-network
    volumes:
        - /jmeter:/jmeter1
  slave:
    build: ./slave
    image: treiro/apache-jmeter-server
    networks:
      - jm-network
    ports:
      - "50000:50000"
      - "1099:1099"
networks:
  jm-network: